package com.hereliesaz.logkitty.ui.diagnosis

import com.hereliesaz.logkitty.ui.delegates.IndexedLogLine

data class IssueDiagnosis(
    val title: String,
    val description: String,
    val explanation: String,
    val suggestedFix: String,
    val evidenceLines: List<IndexedLogLine>
)

object DiagnosisEngine {
    
    fun diagnose(entry: IndexedLogLine, allLogs: List<IndexedLogLine>): IssueDiagnosis {
        val text = entry.text
        
        // Find surrounding context (up to 20 lines before and after)
        val entryIndex = allLogs.indexOfFirst { it.id == entry.id }
        val contextLines = if (entryIndex >= 0) {
            val start = (entryIndex - 20).coerceAtLeast(0)
            val end = (entryIndex + 20).coerceAtMost(allLogs.size - 1)
            allLogs.subList(start, end + 1)
        } else {
            listOf(entry)
        }

        // Basic Rule-Based Diagnosis
        val lowerText = text.lowercase()
        
        if (lowerText.contains("nullpointerexception")) {
            return IssueDiagnosis(
                title = "Null Pointer Exception",
                description = "The application attempted to use an object reference that has the null value.",
                explanation = "This occurs when you call a method or access a field on a variable that hasn't been initialized or has been explicitly set to null.",
                suggestedFix = "Check the stack trace in the evidence to find the exact file and line number. Ensure the object is properly initialized before use, or add a null check.",
                evidenceLines = contextLines.filter { it.text.contains("Exception") || it.text.contains("\tat ") }
            )
        }

        if (lowerText.contains("outofmemoryerror")) {
            return IssueDiagnosis(
                title = "Out of Memory",
                description = "The system ran out of memory while trying to allocate more space for the application.",
                explanation = "This usually happens when loading large images, keeping too many objects in memory, or having a memory leak.",
                suggestedFix = "Use a memory profiler to find leaks. If loading images, use Glide/Coil or downsample them. Check for static references keeping activities alive.",
                evidenceLines = contextLines
            )
        }
        
        if (lowerText.contains("anr in") || lowerText.contains("not responding")) {
            return IssueDiagnosis(
                title = "Application Not Responding (ANR)",
                description = "The application's main thread was blocked for too long.",
                explanation = "Android requires the UI thread to process events quickly. If a long-running operation (like network or database access) is performed on the main thread, the app will freeze.",
                suggestedFix = "Move heavy processing, disk I/O, and network calls to background threads or Coroutines.",
                evidenceLines = contextLines
            )
        }
        
        if (lowerText.contains("connectexception") || lowerText.contains("sockettimeout") || lowerText.contains("unknownhostexception")) {
            return IssueDiagnosis(
                title = "Network Connection Failure",
                description = "The application failed to connect to a network resource.",
                explanation = "This could be due to the device being offline, the server being down, a DNS resolution failure, or a missing INTERNET permission in the manifest.",
                suggestedFix = "Check if the device has internet access. Verify the server URL and status. Ensure <uses-permission android:name=\"android.permission.INTERNET\" /> is in your AndroidManifest.xml.",
                evidenceLines = contextLines
            )
        }

        // Fallback generic diagnosis
        return IssueDiagnosis(
            title = "Log Entry Analysis",
            description = "Detailed view of the selected log entry.",
            explanation = "This log entry was generated by the application or system. Review the surrounding context below to understand what happened before and after this event.",
            suggestedFix = "No specific fix suggested. Analyze the evidence lines.",
            evidenceLines = contextLines
        )
    }
}
